### ISSUE TITLE
Docker context defined in the nodejs RestAPI is incorrect

### ISSUE THREAD

**Issue by sarindaSenevirathne** [wso2/choreo-sample-apps#16]
**Description:**

The given context in the readme file is `nodejs/rest-api/`. But when adding this context to choreo, the validation fails in the component creation window, and the validation is going through when the context is defined as `nodejs/rest-api`.

Shall we change the readme file of this since the users add different context path's when trying to go through the validation and face issues

https://github.com/wso2/choreo-sample-apps/tree/main/nodejs/rest-api

**Comment by chameerar** [comment]
This is fixed in - 47d579571cb506682a4a0f3e8348da9d8762fcfc
Closing as completed
