### ISSUE TITLE
Add additional WSO2 language examples

### ISSUE THREAD

**Issue by BechtelCanDoIt** [wso2/choreo-sample-apps#19]
**Description:**
We should include a Ballerina and a MI Project as well. (Making this more comprehensive.)

**Comment by chameerar** [comment]
More Ballerina and MI samples are added to https://github.com/wso2/choreo-sample-apps
Please note that https://github.com/wso2/choreo-sample-apps will be used as the place to keep the Choreo samples. This repo will be deprecated.
